
# auto-generated by configure
PREFIX = /usr/local
VERSION = 
CC = gcc
CFLAGS = -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -Wno-unknown-pragmas -mmacosx-version-min=10.6 -DUSE_COCOA=1 -I/usr/local/Cellar/libpng/1.6.16/include/libpng16  -I/usr/local/Cellar/zlib/1.2.8/include 
LDFLAGS =  -mmacosx-version-min=10.6 -framework Cocoa -L/usr/local/Cellar/libpng/1.6.16/lib -lpng16  -L/usr/local/Cellar/zlib/1.2.8/lib -lz  -lm
COCOA_READER = 1

